# Generated by Django 4.1.3 on 2022-11-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Celulares',
            },
        ),
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notebooks',
            },
        ),
        migrations.CreateModel(
            name='Televisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Televisores',
            },
        ),
    ]
