# Generated by Django 4.1.3 on 2022-11-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celulares',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notebooks',
            name='image',
        ),
        migrations.RemoveField(
            model_name='televisores',
            name='image',
        ),
    ]
